# Generated by Django 5.1.2 on 2024-10-31 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('street', 'Street Style'), ('advertisement', 'Advertisement'), ('fashionista', 'Fashionista'), ('artist', 'Artist')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
