# Generated by Django 5.1.2 on 2024-10-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
