# Generated by Django 5.1.2 on 2024-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_video_youtube_url_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
