# Generated by Django 5.1.2 on 2024-11-12 18:05

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
