# Generated by Django 5.1.2 on 2024-11-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_youtubevideo_youtubevideourl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YoutubeVideoUrl',
        ),
    ]
