# Generated by Django 5.1.4 on 2025-01-15 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_youtubevideourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=300)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('text_one', models.CharField(max_length=10000)),
                ('text_two', models.CharField(max_length=10000)),
                ('text_three', models.CharField(max_length=10000)),
                ('text_four', models.CharField(max_length=10000)),
                ('text_five', models.CharField(max_length=10000)),
                ('text_six', models.CharField(max_length=10000)),
                ('text_seven', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='partner_company',
            name='name',
        ),
    ]
