# Generated by Django 5.1.4 on 2025-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blog_delete_image_delete_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='faqs_five',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_five_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_one',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_one_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_seven',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_seven_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_six',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_six_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_three',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_three_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_two',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqs_two_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqst_four',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='faqst_four_answer',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
