# Generated by Django 5.1.4 on 2025-01-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_blog_faqs_five_blog_faqs_five_answer_blog_faqs_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='faqst_four_answer',
            new_name='faqs_four_answer',
        ),
    ]
