# Generated by Django 5.1.4 on 2025-01-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_faqst_four_answer_blog_faqs_four_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='faqst_four',
            new_name='faqs_four',
        ),
    ]
